name = "RDC Season 2"
author = "Vang"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86011b8a41461a544242ea27f329b1d1805831f3d74c2725efbdb0dae45d5a76"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
